### PR TITLE
Add Golden Years Lore

### PR DESCRIPTION
**Pull request by sebasptsch**
Christian shares some tales of golden-age progsoc.

### CODE REVIEW

**Review by arduano — APPROVED** [review]
Looks about right lol

**Comment by sunsetkookaburra** [comment]
Is it worth rebasing off of ck's commit, and including both that and this in git history?

**Review by sunsetkookaburra — COMMENTED** [review]
Is it worth rebasing off of ck's commit, and including both that and this in git history?

**Comment by sebasptsch** [comment]
> Is it worth rebasing off of ck's commit, and including both that and this in git history?

Sure, I'm not a git wizard though. I'll give it a shot once I'm back at my PC.

**Comment by sebasptsch** [comment]
> also worth mentioning too that the pr description for #26 is good lore too

Good point, I'll add it lol.

**Comment by sunsetkookaburra** [comment]
I'm happy to put it together now

**Pull request closed without merging**
